/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "home": [],
    "sub.pageone": [],
    "sub.pagetwo": [],
    "dashboard": [],
    "instruments.index": [],
    "instruments.create": [],
    "instruments.store": [],
    "instruments.show": [
        {
            "name": "instrument",
            "required": true,
            "binding": "id"
        }
    ],
    "instruments.edit": [
        {
            "name": "instrument",
            "required": true,
            "binding": "id"
        }
    ],
    "instruments.update": [
        {
            "name": "instrument",
            "required": true,
            "binding": "id"
        }
    ],
    "instruments.destroy": [
        {
            "name": "instrument",
            "required": true,
            "binding": "id"
        }
    ],
    "trades.index": [],
    "trades.create": [],
    "trades.store": [],
    "trades.show": [
        {
            "name": "trade",
            "required": true,
            "binding": "id"
        }
    ],
    "trades.edit": [
        {
            "name": "trade",
            "required": true,
            "binding": "id"
        }
    ],
    "trades.update": [
        {
            "name": "trade",
            "required": true,
            "binding": "id"
        }
    ],
    "trades.destroy": [
        {
            "name": "trade",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
